name: minassat_al_mutahakkamat
description: حوّل هاتفك إلى متحكم للحاسوب (تطبيق مكتبي، لينكس أولًا).
publish_to: none
version: 0.6.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.2.0
  qr_flutter: ^4.1.0
  window_manager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 700
